### ISSUE TITLE
expand single item does nothing

### ISSUE THREAD

**Issue by WORMSS** [juliangruber/brace-expansion#56]
```js
const extensions = extensionList.join(',');
const values = braceExpand(`*.{${extensions}`);
```
If extension list has 2 or more items, you get exactly as you expect
```js
extensionList = ['a', 'b']
// value = ['*.a', '*.b']
```
but if extensionList happens to be a single item
```js
extensionList = ['a'];
// value = ['*.{b}']
// expected value would be ['*.b']
```

As you can see the value is returned 'with' the braces still, you would expect the braces to be removed

**Comment by juliangruber** [comment]
This is consistent with shell behavior:

```bash
$ echo {a,b}
a b
$ echo {a}
{a}
```

`{a}` isn't a valid expansion

**Comment by juliangruber** [comment]
https://github.com/isaacs/node-glob/issues/434#issuecomment-924752880
